### PR TITLE
Added unconnected dropdown to index tree

### PR DESCRIPTION
**Pull request by dmossie**
I added the UnconnectedDropdown to the index tree so that it can be imported from 'react-chart-editor'

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
I'm not sure we want to do this piecemeal at this time... You can still import it right now with a full path, does this not work for you?

**Comment by dmossie** [comment]
Yeah I can use the full path - but I thought this is the functionality you were looking for in our previous conversation. Is there a reason it's not a good idea?

**Comment by nicolaskruchten** [comment]
It's not a bad idea in principle but I would want to implement this for *all* components in one PR, not just `Dropdown`. That's what I mean by "I'm not sure we want to do this piecemeal" :)

**Comment by dmossie** [comment]
Oh ok, I could probably do that pretty quick. Would that be everything in the 'Fields' folder? Also are all of the components ready to be exported?

**Pull request closed without merging**
