### PR TITLE
AxisInterval adjustments 

### PR DESCRIPTION
**Pull request by VeraZab**
part of #803 
- [x] Axes Panel
- [x] Color Bars Panel

### CODE REVIEW

**Comment by VeraZab** [comment]
@nicolaskruchten ready for review..
rearanging my commit order didn't work when force pushing.. I guess github UI orders them by time of commit..this is the order I wanted to have:

pick 811a316 create DTicksInterval to keep visibility rules
pick 97a5958 AxisInterval adjustments for Axes Panel
pick 4bf4821 Add AxisInterval to ColorBars

**Comment by nicolaskruchten** [comment]
Looks great!

Some oddities though, when switching into 'custom' spacing mode and then switching from days to months ... Can we do something smart with the initial value here or... ?


editor

**Comment by nicolaskruchten** [comment]
I think the behaviour above is related to https://github.com/plotly/streambed/issues/11864

**Comment by VeraZab** [comment]
I can reproduce the off default value behavior in this codepen: https://codepen.io/veraz/pen/VqQQGj?editors=0010

**Comment by nicolaskruchten** [comment]
OK, 💃

**Pull request merged**
