### PR TITLE
Notches

### LINKED ISSUE #871: Box notches
missing attrs

### PR DESCRIPTION
**Pull request by dmt0**
Closes #871

### CODE REVIEW

**Comment by dmt0** [comment]
@VeraZab ready for review

**Comment by VeraZab** [comment]
so add notch width too?
Screen Shot 2019-03-13 at 6 02 37 PM

**Comment by dmt0** [comment]
Absolutely, it's already there :)

**Comment by dmt0** [comment]
@nicolaskruchten Any comments on placement in the panel?

**Comment by VeraZab** [comment]
💃

**Comment by nicolaskruchten** [comment]
Lgtm :dancer:

**Pull request merged**
