### PR TITLE
color picker inline

### LINKED ISSUE #626: ColorPicker scroll behaviour
* If a ColorPicker is open and your mouse is *not* over the picker, you can't scroll the pane.
* If a ColorPicker opens at the bottom of a panel, it's not visible and it's hard to scroll into view

I think ideally the colorpicker should open inline like the new colorscale behaviour, instead of popping over.

/cc @cldougl

### PR DESCRIPTION
**Pull request by dmt0**
Closes #626

### CODE REVIEW

**Comment by VeraZab** [comment]
in Percy's `panelTest_StyleColorbarsPanel` test, colorPickers look misaligned

**Comment by VeraZab** [comment]
there seems to be less space.. does this still look ok with an open colorscalepicker?

**Comment by VeraZab** [comment]
A more minimalistic picker, nice, I like!
screen shot 2018-08-07 at 4 53 20 pm

**Comment by nicolaskruchten** [comment]
@VeraZab yeah, this is because it's a fold in a fold and the color pickers are now fixed-width. I think we should accept this one for now :)

**Comment by VeraZab** [comment]
ok well codewise looks ok to me
and could we open an issue for the misaligned colorpickers for another time?

otherwise 💃

**Comment by dmt0** [comment]
Issue for misaligned colorpickers raised:
https://github.com/plotly/react-chart-editor/issues/648

**Comment by nicolaskruchten** [comment]
💃 from me, including the Percy diffs

**Pull request merged**
