### PR TITLE
Traceselector styling

### PR DESCRIPTION
**Pull request by dmt0**
addresses #731

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
💃

**Comment by nicolaskruchten** [comment]
I'm not thrilled about the Percy diff here... ?

**Comment by nicolaskruchten** [comment]
Can you please create a new PR from 1294ed3c7727f43decf0564652752c094ca91719 to `master` and we'll get that merged ASAP and you can keep iterating on this PR? Tacking on commits after 💃 just kinda slows things down actually :)

**Comment by dmt0** [comment]
I'm just gonna remove "fix numeric inputs on IE" from this one - the rest are safe

**Pull request merged**
