### PR TITLE
add histogram axes type

### LINKED ISSUE #555: Creating multiple histogram traces fails
I get "this is embarassing".

### PR DESCRIPTION
**Pull request by dmt0**
closes #555

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Does this fix the "can't create multiple traces" issue?? that's surprising! why does it fail without these lines?

**Comment by dmt0** [comment]
It does indeed.
This is where the error was thrown from:
https://github.com/plotly/react-chart-editor/blob/4f3492ca01daf59b8d86f59aea9fad342a3d7cca/src/lib/getAllAxes.js#L46

**Comment by nicolaskruchten** [comment]
Presumably this makes transforms available to histograms as well right? #556

**Comment by dmt0** [comment]
added `histogram2dcontour`
the rest are fine

**Pull request merged**
